version: "1"
services:
  - type: web
    name: simply-city-1
    runtime: python
    repo: https://github.com/k1nyumatt/simply-city
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn simply_city.wsgi:application
    autoDeployTrigger: commit