version: "1"
services:
  - type: web
    name: simply-city-1
    runtime: python
    repo: https://github.com/k1nyumatt/simply-city
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn simply_city.asgi:application --host 0.0.0.0 --port 8000
    autoDeployTrigger: commit